### ISSUE TITLE
Start nginx in non-daemon mode

### ISSUE THREAD

**Issue by arianvp** [ruuda/miniserver#2]
Nginx supports this. You dont need to jugle with PIDFiles and stuff

**Comment by ruuda** [comment]
The unit is based [on the example unit from the docs](https://www.nginx.com/resources/wiki/start/topics/examples/systemd/). How do can I start it in non-daemon mode? [I don't see a command-line flag for it](https://www.nginx.com/resources/wiki/start/topics/tutorials/commandline/).

**Comment by ruuda** [comment]
Fixed in 81d16eb. The trick was setting `daemon off` in the main config file. Thanks for the suggestion, this simplifies things!
