### ISSUE TITLE
Enable sandbox in nix settings

### ISSUE THREAD

**Issue by arianvp** [ruuda/miniserver#3]
By default nix builds in your system native bash which is an impurity in the build process (but allows for Bootstrap). You can disable this in the nix settings

**Comment by ruuda** [comment]
Where are the Nix settings, and what value should I change?

At least the SHA256 of the output images on Travis are identical to the ones that I build locally.

**Comment by ruuda** [comment]
I’ve been building with sandbox enabled for a long time locally now.
